package com.iucosoft.javaeefinalproject.entities;
// Generated Dec 2, 2024 7:11:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consultatie generated by hbm2java
 */
@Entity
@Table(name = "consultatie",
        catalog = "level4db"
)
public class Consultatie implements java.io.Serializable {

    private Integer id;
    private int idPacient;
    private int idDoctor;
    private String domeniu;
    private Date data_programarii;
//    private String ora_programarii;
    private String adresa;
    private Integer pret;
    private String statut;

    public Consultatie() {
    }

    public Consultatie(Integer id, int idPacient, int idDoctor, String domeniu, Date data_programarii, String adresa, int pret, String statut) {
        this.id = id;
        this.idPacient = idPacient;
        this.idDoctor = idDoctor;
        this.domeniu = domeniu;
        this.data_programarii = data_programarii;
        this.adresa = adresa;
        this.pret = pret;
        this.statut = statut;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "idPacient")
    public int getIdPacient() {
        return idPacient;
    }

    public void setIdPacient(int idPacient) {
        this.idPacient = idPacient;
    }

    @Column(name = "idDoctor")
    public int getIdDoctor() {
        return idDoctor;
    }

    public void setIdDoctor(int idDoctor) {
        this.idDoctor = idDoctor;
    }

    @Column(name = "domeniu", length = 45)
    public String getDomeniu() {
        return this.domeniu;
    }

    public void setDomeniu(String domeniu) {
        this.domeniu = domeniu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_programarii", length = 10)
    public Date getDataProgramarii() {
        return this.data_programarii;
    }

    public void setDataProgramarii(Date data_programarii) {
        this.data_programarii = data_programarii;
    }

////    @Temporal(TemporalType.TIME)
//    @Column(name = "ora_programarii", length = 10)
//     public String getOra_programarii() {
//        return ora_programarii;
//    }
//
//    public void setOra_programarii(String ora_programarii) {
//        this.ora_programarii = ora_programarii;
//    }
    @Column(name = "statut", length = 45)
    public String getStatut() {
        return statut;
    }

    public void setStatut(String statut) {
        this.statut = statut;
    }

    @Column(name = "pret")
    public Integer getPret() {
        return this.pret;
    }

    public void setPret(Integer pret) {
        this.pret = pret;
    }

    @Column(name = "adresa", length = 45)
    public String getAdresa() {
        return adresa;
    }

    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }

    @Override
    public String toString() {
        return "Consultatie{" + "id=" + id + ", idPacient=" + idPacient + ", idDoctor=" + idDoctor + ", domeniu=" + domeniu + ", data_programarii=" + data_programarii + ", adresa=" + adresa + ", pret=" + pret + ", statut=" + statut + '}';
    }

}
