package com.iucosoft.javaeefinalproject.entities;
// Generated Dec 2, 2024 7:11:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor",
        catalog = "level4db",
        uniqueConstraints = {
            @UniqueConstraint(columnNames = "telefon")
            , @UniqueConstraint(columnNames = "email")}
)
public class Doctor implements java.io.Serializable {

    private int id;
    private String nume;
    private String prenume;
    private int telefon;
    private String email;
    private String domeniu;
    private Date start_date;
    private int idUser;

    public Doctor() {
    }

    public Doctor(int id, String nume, String prenume, int telefon, String email, String domeniu, Date start_date, int idUser) {
        this.id = id;
        this.nume = nume;
        this.prenume = prenume;
        this.telefon = telefon;
        this.email = email;
        this.domeniu = domeniu;
        this.start_date = start_date;
        this.idUser = idUser;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nume", length = 45)
    public String getNume() {
        return nume;
    }

    public void setNume(String nume) {
        this.nume = nume;
    }

    @Column(name = "prenume", length = 45)
    public String getPrenume() {
        return prenume;
    }

    public void setPrenume(String prenume) {
        this.prenume = prenume;
    }

    @Column(name = "telefon")
    public int getTelefon() {
        return telefon;
    }

    public void setTelefon(int telefon) {
        this.telefon = telefon;
    }

    @Column(name = "email", length = 45)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "domeniu", length = 45)
    public String getDomeniu() {
        return domeniu;
    }

    public void setDomeniu(String domeniu) {
        this.domeniu = domeniu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "start_date", length = 10)
    public Date getStart_date() {
        return start_date;
    }

    public void setStart_date(Date start_date) {
        this.start_date = start_date;
    }

    @Column(name = "idUser")
    public int getIdUser() {
        return idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    @Override
    public String toString() {
        return "Doctor{" + "id=" + id + ", nume=" + nume + ", prenume=" + prenume + ", telefon=" + telefon + ", email=" + email + ", domeniu=" + domeniu + ", start_date=" + start_date + ", idUser=" + idUser + '}';
    }

    
    
}
