package com.iucosoft.javaeefinalproject.entities;
// Generated Dec 2, 2024 7:11:21 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Domeniu generated by hbm2java
 */
@Entity
@Table(name = "domeniu",
        catalog = "level4db",
        uniqueConstraints = @UniqueConstraint(columnNames = "denumire")
)
public class Domeniu implements java.io.Serializable {

    private int id;
    private String denumire;
    private String descriere;
    private int idDoctor;
    private String doctor;
   

    public Domeniu() {
    }

    public Domeniu(int id, String denumire,  String descriere, int idDoctor, String doctor) {
        this.id = id;
        this.denumire = denumire;
        this.descriere = descriere;
        this.idDoctor = idDoctor;
        this.doctor = doctor;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "denumire", length = 45)
    public String getDenumire() {
        return denumire;
    }

    public void setDenumire(String denumire) {
        this.denumire = denumire;
    }
    
    @Column(name = "descriere", length = 300)
    public String getDescriere() {
        return descriere;
    }
    
    public void setDescriere(String descriere) {
        this.descriere = descriere;
    }

    @Column(name = "idDoctor")
    public int getIdDoctor() {
        return idDoctor;
    }

    public void setIdDoctor(int idDoctor) {
        this.idDoctor = idDoctor;
    }

    @Column(name = "doctor", length = 45)
    public String getDoctor() {
        return doctor;
    }

    public void setDoctor(String doctor) {
        this.doctor = doctor;
    }

    @Override
    public String toString() {
        return "Domeniu{" + "id=" + id + ", denumire=" + denumire + ", descriere=" + descriere + ", idDoctor=" + idDoctor + ", doctor=" + doctor + '}';
    }

}
